- src/Slider.jsx
Reverts react-component/slider#10
> Revert "修复 Slider 初始 `upperBound` 与 `sliderLength` 错误的 Bug。"

- src/Slider.jsx
> 修复 Slider 滑块越界与 step 偏移的 Bug。

- README.md
- examples/simple.js
- package.json
- src/Slider.jsx
- tests/index.spec.js
https://facebook.github.io/react/docs/forms.html
defaultValue defaultIndex 而不是 value,index
> change value to defaultValue

- assets/index.less
- examples/simple.js
- package.json
- src/Slider.jsx
> add slider animation

- src/Slider.jsx
Fix for the circle and bar position when clicking and dragging over the slider bar.
> Sending new value to _start while dragging

- README.md
- assets/index.less
- examples/simple.js
- package.json
- src/Slider.jsx
- tests/index.spec.js
> Step marks fix

- README.md
- examples/simple.js
- package.json
- src/Marks.jsx
- src/Slider.jsx
- src/Steps.jsx
- tests/index.spec.js
> Upgrade api

- examples/simple.js
- src/Handle.jsx
- src/Slider.jsx
I've implemented the `tipFormatter` prop here. `tipFormatter` can be passed as a prop to `slider` and will be propagated to both handles. If present, the value to be formatted will be transformed using the formatter.
> react-component/slider#32 implemented tipFormatter prop

- examples/simple.js
- src/Slider.jsx
Now you can use marks for range sliders. Added a demo and everything works fine.
closes #36
> make range and marks props to work together

- README.md
- examples/marks.js
- package.json
- src/Slider.jsx
> Feat mark as step

- examples/range.js
- examples/slider.js
- package.json
- src/Slider.jsx
- tests/index.spec.js
Close: https://github.com/react-component/slider/issues/54
> fix: value should be aligned if `min` `max` changed

- README.md
- examples/range.js
- src/Slider.jsx
> feat: add `allowCross` property #56

- examples/range.js
- examples/slider.js
- src/Slider.jsx
> fix: crash when rerender #57

- src/Marks.jsx
I need to change styles of the first and last marks. I couldn't find any other way but to put them in correct order.
> put marks in correct order so one can style it

- README.md
- examples/marks.js
- src/Marks.jsx
Close: https://github.com/react-component/slider/issues/50 https://github.com/react-component/slider/issues/76
> feat: support set style of specific mark point

- HISTORY.md
- README.md
- assets/index.less
- examples/v-marks.html
- examples/v-marks.js
- examples/v-range.js
- examples/v-slider.html
- examples/v-slider.js
- package.json
- src/Handle.jsx
- src/Marks.jsx
- src/Slider.jsx
- src/Steps.jsx
- src/Track.jsx
- tests/index.spec.js
- add `vertical` props
- add vertical slider demo: v-marks.html v-range.html v-slider.html
refs:https://github.com/react-component/slider/issues/18
> feat: vertical slider

- src/Slider.jsx
> Import dom util directly.

- src/Slider.jsx
Extend the handle classNames, and provide props so that
upper/lower handles are easily distinguishable in CSS & React.
> Identify upper/lower range handles

- assets/index.less
- examples/custom-handles.js
- src/Slider.jsx
For #135 
- Removed z-indexes from styles.
- Rearranged components
- updated example that used z-indexes
> Removed z-indexes #135

- src/Slider.jsx
As per https://github.com/react-component/slider/pull/137, added a warning when range isn't a multiple of the step.
> Add warning when range isn't a multiple of the step

- README.md
- package.json
Commit 5a4e74e does not change any content of the documentation.
> Increase readability of README

- package.json
> Update rc-utils to 4.0.0

- README.md
- examples/handle.js
- src/createSliderWithTooltip.jsx
> feat: createSliderWithTooltip(Slider, autoDisable)

- examples/range.js
- src/Range.jsx
- tests/Range.test.js
> fix: controlled range

- examples/range.js
- examples/slider.js
- src/Range.jsx
- src/Slider.jsx
- src/createSliderWithTooltip.jsx
> fix: don't show tooltip when disabled

- README.md
- examples/handle.js
- src/createSliderWithTooltip.jsx
> feat: add tipFormatter for Slider/Range with tooltip, close: #232

- assets/index.less
> Use grab and grabbing cursors on handle

- README.md
- src/createSliderWithTooltip.jsx
After createSliderWIthTooltip, slider can get tipProps.  close #276
> add tipProps on tooltipslider

- examples/marks.js
- src/Range.jsx
Bug when trying to move overlapping points
#319
> fix($range): Fix issue with overlapping points

- package.json
My first searches for this component were "react range slider" and
"react range input". So adding these keywords should help this component
to show up in search results.
Also, the closest HTML 5 input to this is `<input type="range">`
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
> Add keywords to improve searchability

- index.html
This PR fixes the link to point to the correct repo
> Point link to correct github repo

- src/Range.jsx
> pushable inaccuracy

- assets/index.less
- src/Handle.jsx
- src/Range.jsx
- src/Slider.jsx
- src/common/createSlider.jsx
- tests/Slider.test.js
> Add click to focus

- src/Range.jsx
- src/Slider.jsx
- src/common/createSlider.jsx
- src/utils.js
- tests/common/createSlider.test.js
> Protect against Infinite and non-numeric values when instantiation

- src/Handle.jsx
close ant-design/ant-design#15324
> Fix Range Slider cannot drag after a drag behavior

- src/utils.js
- tests/utils.test.js
> Fix utils.getClosestPoint() to ensure value in range

- src/Range.jsx
- src/Slider.jsx
- tests/Range.test.js
- tests/Slider.test.js
https://github.com/ant-design/ant-design/issues/15640
>  Support onAfterChange when key pressed

- package.json
- src/Range.jsx
- src/Slider.jsx
- src/common/createSlider.jsx
- src/createSliderWithTooltip.jsx
- src/utils.js
- tests/Range.test.js
- tests/common/createSlider.test.js
- tests/utils.test.js
https://github.com/ant-design/ant-design/issues/9792
fixes #587
fixes #562
> Migrate react lifecycle

- .editorconfig
Handle *.jsx files like *.js files.
> EditorConfig: *.jsx files

- assets/index.less
- src/Range.jsx
- tests/Range.test.js
[#19879](https://github.com/ant-design/ant-design/issues/19879)
> fix(#19879): focusing the wrong handle when using range

- src/common/createSlider.jsx
- tests/Slider.test.js
fix https://github.com/ant-design/ant-design/issues/22526
> fix: null value should not out of range

- src/Range.tsx
- src/Slider.tsx
- src/common/createSlider.tsx
- src/createSliderWithTooltip.tsx
- src/index.tsx
- src/interface.ts
- tests/type.test.tsx
close https://github.com/react-component/slider/issues/656
改动稍微有点大，看看有没有漏的
@zombieJ @afc163
> refactor: optimize type definition

- src/common/Steps.tsx
- src/common/createSlider.tsx
- src/interface.ts
- tests/type.test.tsx
> fix: add missing props

- src/Range.tsx
- src/Slider.tsx
- src/common/createSlider.tsx
- tests/common/SliderTooltip.test.js
- tests/common/createSlider.test.js
close https://github.com/ant-design/ant-design/issues/27677
改为只有 min 和 max 改变边界时才触发。
> fix: extra onChange when value out of range

- README.md
- docs/examples/range.jsx
- docs/examples/vertical.jsx
- src/Range.tsx
- src/Slider.tsx
- src/common/Track.tsx
- src/common/createSlider.tsx
- src/interface.ts
- tests/Range.test.js
https://github.com/ant-design/ant-design/issues/25517
> add dragableTrack

- src/Slider.tsx
Reverts react-component/slider#741
> Revert "Update Slider.tsx"

- src/Slider.tsx
- tests/Slider.test.js
close https://github.com/ant-design/ant-design/issues/34677
> fix: onAfterChange should called with number if not range

- src/Slider.tsx
- src/index.tsx
> chore: export SliderRef

- src/hooks/useOffset.ts
- tests/Range.test.js
close https://github.com/react-component/slider/security/code-scanning/5
close https://github.com/react-component/slider/security/code-scanning/3
> fix: code scanning alerts

- package.json
- src/Slider.tsx
This help outside correct handle focus logic.
> enhance: Make sure slider trigger focus event on track click

- docs/examples/marks.tsx
- src/Slider.tsx
- tests/marks.test.js
close https://github.com/ant-design/ant-design/issues/49997
> fix: onChangeComplete should be triggered when click marks
