assets/index.less, examples/marks.js, package.json, src/Handle.jsx, src/Marks.jsx, src/Slider.jsx, src/Steps.jsx, tests/index.spec.js
这个 PR 依赖于之前提交的 https://github.com/react-component/slider/pull/40
不兼容的修改主要有两点：
1. 移除了之前 deprecated 的 `isIncluded` `withDots`
1. 解绑 `marks` 和 `step`，现在 `marks` 是一个 Object 其中 key 为 `Number`，value 为 `String`
antd 那边稍后会做一层包装，以兼容旧版。
Close: https://github.com/react-component/slider/issues/26
=> 3.0.0 beta

src/Marks.jsx
Now even short enough labels can't fit into one string.
I have this in my app:
With my fix, it would be better. Borders are especially have been added to show mark constraints:
=> reduce gaps between marks

README.md, examples/slider.js, src/Slider.jsx
We're using this component in an application where we display the actual value of the slider in a separate text box. We didn't want to show the tip in this case but there didn't seem to be any way to simply hide it. I thought setting the tipFormatter prop to null would be a sensible way to force the tip to be hidden.
=> If tipFormatter is null, don't show the tip

README.md, examples/custom-handles.html, examples/custom-handles.js, src/Slider.jsx
This is my attempt to solve #63  starting from #68 
It's basically the same, I changed the API in order to pass the custom handle directly as prop, using internally `cloneElement` instead of the function, as suggested by @yiminghe 
As shown in the example:
```javascript
<Slider Handle={<MyHandle />} />
```
which I agree is much more customizable
Let me know, and in case, I guess we just need to update the docs
=> Allow to pass custom handle components

src/Slider.jsx
Not sure if this is something that you are interested in, but I wanted it for a project, so I though I would at least try to nudge it back upstream.
Basically the issue is that if you right click on the slider (opening the context menu), you either did so for a reason other than to modify the slider value, or it was an accident altogether, so it should probably be ignored.
I tried to write a test for this with `Simulate.mouseDown` using `ReactTestUtils`, but I wasn't able to get `Simulate.mouseDown` to actual trigger `onMouseDown` on the `Slider`. If you want a test for this and have a suggestion on how to accomplish one, I'm happy to go back and try again.
=> Ignore right button on mousedown

package.json
Many modules in npm are starting to expose their css entry files in their `package.json` files. This allows tools like `postcss-import`, `parcelify`, `npm-css`, `rework-npm` and `npm-less` to import *rc-slider* straight from node_modules directory.
Example:
```css
@import 'rc-slider';
```
The same way as `main` node, but for css 😄 
Reference:
https://github.com/twbs/bootstrap/pull/12441
=> Add 'style' node to package.json

README.md, examples/range.js, src/Slider.jsx, tests/index.spec.js
Added support for more than 2 handles using `<Slider range={<number>} />`.
`number` is the number of tracks (i.e., `number === nHandles + 1`).
Example of `<Slider range={2} value={[25, 50, 65]} />`:
>CSS is different because of my application custom stylesheets...
I also need pushable handles in my webapp...
The `pushable` property can be set to `true` to enable handle-pushing. When it is a number, the number represents the minimum distance between handles when pushing (`pushable={true}` is equivalent to `pushable={1}`).
Example of `<Slider range={3} pushable={10} defaultValue={[10, 25, 45, 70]} />`:
It also works correctly with any weird combination of `marks` and `step`.
- Instead of `lowerBound` and `upperBound`, the `Slider`'s state was changed to store a `bounds` array.
- Pushable …
=> Add multi-range support

src/Slider.jsx, tests/index.js
This PR fixes react-component/slider/issues/144
I tried to lint but linting fails because of modules not installed and wrong config values.
Also tried using `ReactTestUtils.Simulate` for tests without success.
At least I tried...
=> fixed `onChange` which fired on every mousmove, added test

src/Slider.jsx, tests/index.js
When a user initially clicks on a handle, the slider positions the handle so the center is under the pointer. If the user doesn't click exactly in the center of the handle, this causes the handle to "jump" and changes the slider's value, which may not be what the user intended.
This PR updates the position logic to account for the difference between the initial handle position and the initial pointer position, so the handles are positioned relative to the delta between their origin and the pointer origin. This ensures the slider value doesn't change until the pointer moves.
Let me know if there's anything I should add to the PR. Thanks.
=> Account for position difference between handle and event origin when dragging

README.md
I was getting errors on my unit tests when trying to import the <Rcslider /> component. Turns out the correct name of the component is Slider. I felt the Usage section of the Readme was a bit misleading.
=> Update Usage section to use accurate component name

README.md, src/Handle.jsx, src/Slider.jsx
This is useful when working with an array of objects:
```jsx
const items = [{ name: 'A', value: 25 }, { name: 'B', value: 60 }];
const tipFormatter = (value, index) => items[index].name;
<Slider
value={items.map(item => item.value)}
tipFormatter={tipFormatter}
/>
```
By the way, I really wish that this package could be installed as a git source. I totally understand the desire to keep build files out of the repo, but not committing `lib` is very inconvenient. For me to use the fork I've created, I basically have to vendor the entire project.
=> Make the second argument to tipFormatter the index of the handle

src/createSlider.jsx, tests/common.test.js
How to reproduce:
1. Start dragging of slider
2. Move mouse to the left of the slider (or above the slider in a case of the vertical slider).
3. You will see that the slider value will be bigger than min value (and it starts moving in the right direction).
I guess it is unexpected behaviour.
=> Fix slider value calculation

src/createSlider.jsx, tests/common.test.js
It's possible for the ref to be undefined, especially when using async batching strategies.
For example:
```
TypeError: Cannot read property 'getBoundingClientRect' of null
at getSliderStart(node_modules/rc-slider/lib/createSlider.js:170:0)
at calcValueByPos(node_modules/rc-slider/lib/createSlider.js:196:0)
at onMove(node_modules/rc-slider/lib/Slider.js:111:0)
at callback(node_modules/rc-slider/lib/createSlider.js:120:0)
at batchedUpdates(ui/utils/ReactRAFBatchingStrategy.js:29:13)
at unstable_batchedUpdates(node_modules/react-dom/lib/ReactUpdates.js:97:0)
at call(node_modules/rc-util/lib/Dom/addEventListener.js:21:0)
at apply(node_modules/add-dom-event-listener/lib/index.js:17:0)
at apply(node_modules/raven-js/src/raven.js:278:0)
```
=> fix: ensure ref is present before using

assets/index.less
`.rc-slider-handle-active` was removed in [9ebe2de](https://github.com/react-component/slider/commit/9ebe2de0cbf13647dc2f49cf4ae45e5ff8b07eba#diff-4dfae13f53a5af8d1382d6a704e2ec40L384) which is why the active style wasn’t working. Instead of programmatically adding an active class, I simply use the `:active` pseudo-class now.
=> Fix handle’s active style

examples/handle.js, src/Handle.jsx, src/Range.jsx, src/Slider.jsx, src/common/createSlider.jsx, src/createSliderWithTooltip.jsx, tests/__snapshots__/Range.test.js.snap, tests/__snapshots__/Slider.test.js.snap
https://github.com/ant-design/ant-design-mobile/pull/1179
=> support aria

src/createSliderWithTooltip.jsx
This fixes an issue with `createSliderWithTooltip()` where multiple tooltips will be shown at once if the mouse is dragged over two or more handles quickly.
Reproduced here:
http://codepen.io/anon/pen/jmEPxV?editors=0011
This was due to the fact that multiple setStates would fire back to back and the second would apply old state values. Passing a function to setState (atomic update) was the fix.
=> Fix issue with multiple tooltips showing

README.md, examples/range.js, examples/slider.js, package.json, src/Handle.jsx, src/Range.jsx, src/Slider.jsx, src/common/Track.jsx, src/common/createSlider.jsx, src/createSliderWithTooltip.jsx
ref https://github.com/react-component/slider/pull/255#issuecomment-307011427
@silentcloud  @benjycui 
Take a look at new api propose.
- The `minimumTrackStyle` and `maximumTrackStyle` will be deprecate at `rc-slider@9.x`. But will remain at this 8.x minor version upgrade, since wait to`antd@3.x` and `antd-mobile@2.x` major version is too late.
- suggest use `handleStyle`, `trackStyle `, `railStyle ` to custom style
@silentcloud Let me konw whether this will have influence to tiny-app.
| Name         | Type    | Default | Description |
| ------------ | ------- | ------- | ----------- |
| minimumTrackStyle | Object |  | please use  `trackStyle[0]` instead. (`only used for slider, just for compatibility , will be deprecate at rc-slider@9.x `) |
| maximumTrackStyle | Object |   | please use …
=> refactor: trackStyle & handleStyle & railStyle

src/common/createSlider.jsx, tests/common/createSlider.test.js
Fixes #279. Includes #289 with a small refactor and also resolves the failing tests.
=> Support sliders with CSS scale()

README.md, examples/slider.js, src/common/Steps.jsx, src/common/createSlider.jsx
I was thinking something like this for adding styling to the dots
=> Added dotStyle and activeDotStyle

assets/index.less, src/Handle.jsx, src/Range.jsx, src/Slider.jsx, src/common/createSlider.jsx, src/utils.js, tests/Slider.test.js, tests/__snapshots__/Range.test.js.snap, tests/__snapshots__/Slider.test.js.snap
As promptly discussed in issue #131, I created some basic accessibility for the Slider. I implemented the keyboard behaviour as my personal best guess of how it should work. 
> Note, this is a work in progress but I wanted to share my changes already.
=> Basic slider accessibility

src/common/createSlider.jsx
I noticed a problem that events binding to document. It has problem in frames that has they own document. It is better to use _el.ownerDocument_ to add all slider event listeners.
=> change event binding to slider ownerDocument

package.json
Addresses https://github.com/react-component/slider/issues/333#issuecomment-337313098
=> Increasing minimum version of rc-tooltip dependency that is compliant with react 16

src/common/createSlider.jsx
=> removeEvent on Mouseup and before addEvent

assets/index.less
Settings margin-left to the exact same value for :first-child, :last-child and the regular `.rc-slider-dot` seems redundant, and doesn't do anything.
=> Remove redundant css

src/common/Marks.jsx, tests/common/marks.test.js
Use-case: I have a slider bar for percent values. I use marks for
every allowed value (e.g. values from 2 to 5 are not allowed).
Displaying every mark label would flood the UI. So there are mark labels
displayed only for every 10th step, which also works fine without this
change (using: {10: '10%', 11: ''}).
This change just optimizes that there are no empty DOM nodes rendered.
=> Do not render empty mark labels

src/common/createSlider.jsx
Fixes #338 
Since onTouchStart() et al are not called in snapshot testing, it is easy to avoid the crash.
=> fix snapshot testing with storyshots, enzyme, react-test-renderer

README.md, src/Handle.jsx, src/Range.jsx, src/Slider.jsx, tests/Range.test.js, tests/Slider.test.js
Basic implementation of `tabIndex` prop on the Handle component. Both Slider.js and Range.js also implement `tabIndex,` but in both cases it's simply passed through to the Handle. I've also updated the test suite with some simple checks to make sure `tabIndex` gets set properly on Handle from its parent. I've updated the README doc as well.
The default value for `tabIndex` is preserved (it's still "0"), so this change should not break any existing uses.
This is a fix for https://github.com/react-component/slider/issues/353
cc: @paranoidjk
=> Allow tabIndex to be set explicitly on Handle

src/createSliderWithTooltip.jsx
If need always to show toolTip value.
I want to show toolTip always. But I can't change this state. It works only on hover. 
https://github.com/react-component/slider/blob/master/src/createSliderWithTooltip.jsx#L61
I added this changes because custom toolTip doesn't work.
https://github.com/react-component/slider/issues/377
=> Added forceVisible parameter to tipProps.

examples/slider.js
Greetings!
I'm not usually picky when it comes to grammar errors, but I thought this one is quite silly.
> old api, will be <strong>deperacete</strong> -> old api, will be <strong>deprecated</strong>
=> Fixed a typo on 'slider' example page. ('deperacate' -> 'deprecated')

src/common/Track.jsx
Had an issue when range component placed inside dropdown which controlled by visibility property. And in result when dropdown is hidden rc-slider-track still visible.
=> Remove visibility property from rc-slider-track

src/common/Marks.jsx, src/common/createSlider.jsx
This is to fix the usability issue of clicking mark label sometimes unable to update the slider input with the correct mark value.
https://github.com/react-component/slider/issues/213.
=> Add click handler to mark in order to change the slider value to mark value when the mark label is clicked

src/Range.jsx, tests/Range.test.js
Range component should only update the values that are out of range.
Issue: https://github.com/react-component/slider/issues/328
=> Only update values that are out of range.

src/common/createSlider.jsx, src/utils.js
When I use horizontal slider, and page is scrolled, clicking to slider incorrectly calculates new value:
This is reproducible on the slider demo page http://react-component.github.io/slider/examples/handle.html
_Unfortunately, cursor is not displayed, but I'm clicking to the slider and handle is placed in incorrect place after click._
How to reproduce
1. Open a [demo page](http://react-component.github.io/slider/examples/handle.html)
2. Resize it until horizontal scroll is displayed
3. Scroll a little bit horizontally
4. Click by mouse on any point of sliders
Result: value is incorrectly calculated and slider jumps to incorrect position, not where mouse was clicked
Expected result: mouse click point exactly the same as where handle of the slider is placed.
Proposed solution adds …
=> Add window.scrollX to fix bug with incorrectly calculated value with scrolled page

examples/slider.js, src/Slider.jsx, src/common/createSlider.jsx, tests/Slider.test.js, tests/__snapshots__/Slider.test.js.snap
As discussed in #356 I added the possibility to use `null` as value for `Slider` component (see example in /examples/slider.html ).
=> Feature: add the possibility to use null as value for Slider

src/Range.jsx, tests/Range.test.js
closes #466 
On figuring out how the code works, I'm not sure what the previous test case was testing:
https://github.com/gpinhey/slider/blob/110ef4e48e7c5262db21bd0dc43bdbe6dcead2ef/tests/Range.test.js#L83-L89
When `step` is set, shouldn't it be expected that the `value` prop will be aligned to that step? While the test confirms that `onChange` is fired with the values not aligned to step, the component's `nextBounds` are different from what is communicated via `onChange`.
I think `onChange` should be fired whenever `nextBounds` was modified from the provided `value` (whether controlled via the `value` prop or uncontrolled via `state.bounds`).
=> Use current value in Range when clipping to min/max

src/common/createSlider.jsx, tests/common/createSlider.test.js
Currently there is no invocation of `onAfterChange` when there is a click on the label of a mark.
To me this looks like a bug. I expect the same behaviour as clicking on the dot (representing the value) itself.
In order to achieve the expected invocation I call `onEnd` when a mark label is clicked. Since I only use the Slider I'm not really sure if the expected behaviour for the Range component might be different.
=> Added onAfterChange call on mark label click

examples/handle.js, src/utils.js, tests/Slider.test.js
We currently have a component that may have fixed values, i.e the user can choose between the values `10, 30, 60, 90, 100`.
To achieve that, the component takes the following props:
````
<Slider 
marks={{10: 10, 30: 30, 60: 60, 90: 90, 100: 100}}
min={10}
step={null}
/>
````
This breaks the current accessibility support, which increases/decreases the component's value according to the steps.
It would be amazing if we could implement support to change it to the next mark when step is set to null.
=> Add keyboard support for components that have fixed values and no step

src/Range.jsx, tests/Slider.test.js
Fix https://github.com/ant-design/ant-design/issues/14962
=> Fix Range crash when press arrow keys (left, right, up, down)

src/Handle.jsx, src/Range.jsx, tests/Range.test.js, tests/Slider.test.js
When I click on the mark in the slider a focus event occurs. And if I want to click on another mark, then I will have to click twice. It is not right. As a solution, we should be able to pass a null. In this case, the attribute tabindex will not be added and the focus events and blur will not occur.
=> Add ability for pass null in tabIndex prop

examples/slider.js, src/Slider.jsx
When using min, max and step values like 
min = 1
max = 99
step = 10
then Slider may end up returning a value higher than max.
Example: slide down to 1 then slide up to max - value becomes 101
Also updated 'dynamic bounds' slider example
The bugfix: Slider.jsx, line 69
=> Prevent slider from returning value higher than max

examples/slider.js
Hi,
in `examples/slider.js`, deprecated props `maximumTrackStyle` and `minimumTrackStyle` are still used.
In Typescript environment, these props cannot be used anymore, and this may cause some confusions.
This PR fixes this problem.
Thanks.
=> Fix deprecated prop name

README.md
It wasn't obvious that you can pass any `ReactNode` as the mark content.
=> Improve `marks` prop docs

src/Range.jsx
Fixing issue described in [529](https://github.com/react-component/slider/issues/529)
=> onAfterChange won't trigger for left handle when clicking on track - issue #529

src/common/createSlider.jsx
Fixes a case where clicking a `Mark` on a `Slider` causes `onAfterChange` handler to be called with old value, because `setState` isn't done with updates yet.
This edit ensures `onEnd` is called only after the change has been applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/react-component/slider/554)
=> Fix Slider Mark click values for onAfterChange

src/Range.jsx
It seems the current Range component has a bug when using a keyboard to change values. This is how it looks like
This pull request fixes the issue
=> Fix Range component keyboard usage

src/Range.jsx
This bug fix was quite simple. Please review it and let me know if I need to change anything.
I'm just a little worried about this part : `if (Math.abs(bounds[closestBound + 1] - value) < Math.abs(bounds[closestBound] - value))`. I don't quite get why it's here and if my changes can affect it.
=> Fix #575: Range issue with pushable={0}

README.md, src/Handle.jsx, src/Range.jsx, src/Slider.jsx, tests/Range.test.js, tests/Slider.test.js
Adds the option to set the following aria attributes on the slider/range handle:
* `aria-label`
* `aria-labelledby`
* `aria-valuetext` (via the `ariaValueTextFormatter` prop)
For more information on using aria attributes with sliders, see:
https://www.w3.org/TR/wai-aria-practices-1.1/#slider
These are added as props on the `Handle` component.  I also added them as props to `Slider` and `Range` -- they just get passed through to the `Handle`.  If you think it's adding too much clutter to `Slider` and `Range`, we could drop those props and have people use a handle generator function to pass them to the `Handle`.
If the props aren't set, the attributes are omitted from the handle element.
Also added info about the props to the readme, and some tests to make sure the attributes get set on the …
=> Add more aria attributes to the handle

README.md, examples/slider.js, examples/vertical.js, src/Slider.jsx, src/common/Track.jsx, src/common/createSlider.jsx, tests/Slider.test.js
By default the track starts from `min` value in Slider component. With new `trackStart` prop you can define where the track starts from.
Examples:
See #488
=> trackStart prop for Slider component

src/createSliderWithTooltip.jsx, tests/common/createSlider.test.js
#598 
* follow the issue #598
* add the possibility to add a get container method to fix the relative parent of the slider's tooltip
=> feat(create-slider-with-tooltip): add get container method

src/common/Marks.jsx, tests/Slider.test.js
在reverse时，设置最小数不为0，可复现bug；
附上reverse前后截图；
=> fix: fix marks position

assets/index.less, src/Handle.jsx
Ref https://github.com/ant-design/ant-design/issues/22128
Before: 
After:
@afc163 We need to fix this from rc-slider's side.
=> fix: fix vertical handle transform

src/Slider.tsx
When using null step Slider in Typescript, the linter complains that `step` cannot be null when used:
```
export default () => (
<div>
{/*Type 'null' is not assignable to type 'number | undefined'*/}
<Slider step={null} /> 
</div>
)
```
In the API is is clearly mentioned that step can be null:
| Name         | Type    | Default | Description |
| ------------ | ------- | ------- | ----------- |
| step | number or `null` | `1` | Value to be added or subtracted on each step the slider makes. Must be greater than zero, and `max` - `min` should be evenly divisible by the step value. <br /> When `marks` is not an empty object, `step` can be set to `null`, to make `marks` as steps. |
This PR is to fix the type definition so that it doesn't show the error above.
=> fix: allow step prop to be null for typescript

src/Range.tsx, tests/Range.test.js
This PR implements the changes suggested in #690 to fix how `Range` incorrectly handles the dynamic de/increase in the number of handles.
=> Fix Dynamically Decreasing Number of Handles Results in Incorrect Handles

src/interface.ts
I'm getting this error.
```
node_modules/rc-slider/lib/Slider.d.ts:3:18 - error TS2430: Interface 'SliderProps' incorrectly extends interface 'GenericSliderProps'.
Types of property 'step' are incompatible.
Type 'number | null | undefined' is not assignable to type 'number | undefined'.
Type 'null' is not assignable to type 'number | undefined'.
3 export interface SliderProps extends GenericSliderProps {
~~~~~~~~~~~
```
This is breaking my build so it would be nice if you could release a new patch version after this PR. Thanks.
=> Fix type definition bug

README.md, examples/handle.jsx, src/common/SliderTooltip.tsx, src/createSliderWithTooltip.tsx, src/index.tsx, tests/common/SliderTooltip.test.js, tests/type.test.tsx
close https://github.com/react-component/slider/issues/693
=> fix: keep tooltip align with handle when dragging

src/Slider.tsx
In relation to issue #682, i updated the lower and upper bounds relative to the startPoint
=> update getLowerBound and getUpperBound to check startPoint prop

src/utils.ts, tests/utils.test.js
修复 getClosestPoint 函数由于浮点数计算精度问题导致的 bug [#27571](https://github.com/ant-design/ant-design/issues/27571)
=> fix bug: slider cannot drag to max value

src/common/createSlider.tsx, src/createSliderWithTooltip.tsx, src/index.tsx
fix https://github.com/react-component/slider/issues/657
添加 SliderProps、RangeProps 和 HandleProps 导出
=> chore: export slider、range and handle  props interface

.umirc.ts, README.md, package.json
close https://github.com/react-component/slider/issues/744
close https://github.com/react-component/slider/issues/735
=> chore: fix dumi website

src/Range.tsx
This is the same like #691 where it was fixed for `Slider` but `Range` seems to have been forgotten. Fixes #739 #652 #574
=> Allow Range prop `step` to be null in Typescript

src/Range.tsx
track dragging implementation was hardcoded for a range of 0-100, causing issues with dragging for other ranges. 
codepen demonstrating the issue https://codepen.io/bjornuppeke/pen/JjRzxdE
Fixes https://github.com/react-component/slider/issues/740
=> fix dragabbleTrack for non-default ranges

src/Range.tsx, src/Slider.tsx, tests/type.test.tsx
Fixes: https://github.com/react-component/slider/issues/726
=> Fixed types for ariaValueTextFormatter

src/Slider.tsx, tests/Slider.test.js
In version 10.0.0-alpha.5, when you click the rail, the following events are fired: `onChange`, `onAfterChange`. This PR ensures that `onBeforeChange` will be fired as well.
Background: there has historically been some bugginess around which events are fired when clicking on the rail. In version 8.6.1, we correctly fired all three: `onBeforeChange`, `onChange`, `onAfterChange`. 
In version 9.7.5, we fired too many events when clicking on the rail: `onBeforeChange`, `onChange`, `onBeforeChange`, `onAfterChange`.
See this issue for more people that have been affected by these event firing inconsistencies: https://github.com/react-component/slider/issues/492
=> ensure onBeforeChange is called when clicking the rail

README.md, src/Slider.tsx, src/Steps/Dot.tsx, src/Steps/index.tsx, tests/common.test.js
Same as PR #828, but with added tests.
close #828
=> Allow callback for "dotStyle" and "activeDotStyle" props - with tests

src/Steps/index.tsx, tests/common.test.js
resolve ant-design/ant-design#36387
=> fix: page crash when dots is true and step is null

README.md, docs/examples/handle.tsx, src/Handles/Handle.tsx, src/Slider.tsx, src/context.ts, tests/Range.test.js
close https://github.com/ant-design/ant-design/issues/21695
=> feat: add disableKeyboardEvents

assets/index.less
让 silder 本身的标记点可以触发相关的事件不会出穿透点击事件，从而修复小的标记点实际触发范围的异常
issue: https://github.com/ant-design/ant-design/issues/40288
=> fix: dot wrong event of pointer https://github.com/ant-design/ant-design/issues/40288

src/Handles/Handle.tsx, tests/Range.test.js, tests/__snapshots__/Range.test.js.snap, tests/__snapshots__/Slider.test.js.snap
The `aria-orientation` attribute indicates whether the element's orientation is horizontal, vertical.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-orientation
=> fix(Handle): add aria-orientation on handles

assets/index.less, src/Tracks/Track.tsx, tests/Range.test.js
- fix https://github.com/ant-design/ant-design/issues/42628
- fix #907
=> fix: slider track draggale range height/width error

assets/index.less
- fix https://github.com/react-component/slider/issues/912
=> fix: error z-index with track handle

docs/examples/debug.tsx, docs/examples/marks.tsx, src/Handles/Handle.tsx, src/Handles/index.tsx, src/Slider.tsx, tests/Range.test.js, tests/Slider.test.js, tests/common.test.js
close https://github.com/ant-design/ant-design/issues/46158
=> fix: onAfterChange should not trigger when click on track

package.json
I noticed some CI was failing this morning, complaining about an unavailable import. 
It seems that [`src/hooks/useDrag.ts`](https://github.com/react-component/slider/blob/master/src/hooks/useDrag.ts) has started using `useEvent` from `rc-util` which has only become available from version 5.36, so the minimum version in `package.json` has to be increased.
Let me know if there's anything else I should do 😀
=> chore(deps): increase rc-util minimum to 5.36 due to usage of useEvent

src/Handles/index.tsx, src/Slider.tsx, src/hooks/useDrag.ts, tests/Range.test.tsx, tests/Tooltip.test.js
过去 tooltip render 的 help 是始终存在的，但是当支持 editable 后，元素是可以被全部移除掉的。这个时候 tooltip 就应该一同被清理掉了。
=> fix: Tooltip logic

src/hooks/useDrag.ts, tests/Range.test.tsx
preventDefault 导致无法 focus，应该改成 css 来实现禁止选中。回滚
=> revert: prevent default

docs/examples/editable.tsx, src/context.ts, src/hooks/useDrag.ts, src/index.tsx
对于渐变色而言，点的位置包含了颜色信息。加个内部接口出来。如果有同类需求，未来可以考虑变成正式的接口。
=> chore: add internal hooks
